# pyproject.toml
[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hGRS"
version = "1.1.1"
description = "hGRS processor for atmospheric correction of high-spatial resolution and multispectral satellite images"
#readme = "pypi_README.rst"
authors = [{ name = "Tristan Harmel", email = "tristan.harmel@gmail.com" }]

license = "Apache-2.0"
license-files = ["LICENSE"]

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["PRISMA","EnMAP","atmospheric correction", "EO satellite"]
requires-python = ">=3.9"
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"hgrs"= ['*.yml','data/lut/*.nc', 'data/aux/*']

[tool.setuptools.exclude-package-data]
"*" = [".gitattributes"]

[project.scripts]
hgrs_prisma = "hgrs.run_prisma:main"
hgrs_enmap = "hgrs.run_enmap:main"

#dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/Tristanovsk/hgrs"
Documentation = "https://hgrs.readthedocs.io"